### PR TITLE
Add python3 version of the extract_firmware script

### PR DESCRIPTION
**Pull request by lgbaldoni**
Python 2.x will only be supported until the end of the year and many distributions are removing it.
I tested this script with every supported driver version and the outputs all match, perhaps someone will find it useful.

### CODE REVIEW

**Comment by imirkin** [comment]
Would it be possible to make a single script which works for both? Is it just as simple as adding () to print, or is there more?

Also, please do this for https://github.com/envytools/firmware which is where I think it makes more sense for this script to live. I only put it here since originally it really was just for VP2 firmware, but it grew.

**Comment by lgbaldoni** [comment]
Right now it works with both (2.7 at least), but it's memory inefficient with py2.
Having clean code on both would require a few conditionals and my python "consultant" is not willing to do that, sorry.

Should I create a pull request on the other project?

**Comment by imirkin** [comment]
Do you mean zip vs izip? It's like a handful of entries, we can handle the memory inefficiency. Having one script is very nice, IMO.

And yes, please make a PR for the other project.

**Comment by lgbaldoni** [comment]
Done

**Pull request closed without merging**
